# Generated by Django 2.2.6 on 2023-01-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0005_auto_20230113_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='pessoa',
        ),
    ]
